apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-service
  template:
    metadata:
      labels:
        app: helloworld-service
    spec:
      containers:
      - name: helloworld-service
        image: vyshnavidp/hello-world-service:latest
        ports:
        - containerPort: 8002
